canton.parameters.enable-alpha-state-via-config = yes
canton.parameters.state-refresh-interval = 5s
canton.participants.sandbox {
  ledger-api.address = 0.0.0.0
  ledger-api.port = 6865
  ledger-api.auth-services = [
    {
      type = jwt-jwks
      url = "http://mockauth1:8080/mockissuer1/jwt"
    },
    {
      type = jwt-jwks
      url = "http://mockauth2:8080/mockissuer2/jwt"
    }
  ]
  admin-api.address = 0.0.0.0
  admin-api.port = 6866
  http-ledger-api.address = 0.0.0.0
  http-ledger-api.port = 7575
  alpha-dynamic {
    parties = [
      {party = "alice"}
      {party = "bob"}
    ],
    idps = [
      {identity-provider-id = "mockauth1", issuer = "http://localhost:8080/mockissuer1", jwks-url = "http://mockauth1:8080/mockissuer1/jwks"},
      {identity-provider-id = "mockauth2", issuer = "http://localhost:8081/mockissuer2", jwks-url = "http://mockauth2:8081/mockissuer2/jwks"},
    ],
    users = [
      {user = "Alice", primary-party = "alice", identity-provider-id = "mockauth1", rights = {act-as = ["alice"]}},
      {user = "Bob", primary-party = "bob", identity-provider-id = "mockauth2", rights = {act-as = ["bob"]}}
    ]
  }
}