canton {
  features.enable-testing-commands = yes
  remote-participants {
    sandbox {
      ledger-api.port = 6865
      ledger-api.address = canton
      admin-api.port = 6866
      admin-api.address = canton
    }
  }
}